### ISSUE TITLE
mcmc_mclmc / mcmc_adjusted_mclmc break under blackjax >= 1.5 (mclmc_kernel adaptation interface change)

### ISSUE THREAD

**Issue by suchethac** [suchethac/tengri#1177]
## Summary

On a **fresh install** (which resolves `blackjax` 1.6, within the `blackjax>=1.0` pin), `fitter.run("mcmc_mclmc")` and `fitter.run("mcmc_adjusted_mclmc")` crash. They work on the maintainer's pinned **blackjax 1.3**, so the breakage is invisible in a pinned dev env — but CI installs `blackjax>=1.0` → latest, and every downloader gets 1.6.

Found during the fresh-user audit (PR #1165). Sibling `mcmc_ghmc` had a related but shallower drift (arg reorder) and is fixed there via keyword args; these two need a deeper port, hence this issue.

## Errors (blackjax 1.6, D≈5 photometry model)

- `mcmc_mclmc`: `TypeError: run_mclmc.<locals>.kernel_factory() got an unexpected keyword argument 'rng_key'`
- `mcmc_adjusted_mclmc`: `TypeError: run_adjusted_mclmc.<locals>._kernel_for_adaptation() got an unexpected keyword argument 'logdensity_fn'`

(Adding `logdensity_fn=ld_1arg` to the `*_find_L_and_step_size` calls is necessary but **not** sufficient — the kernel interface itself changed.)

## Root cause — the `mclmc_kernel` interface changed

**blackjax 1.3** (works today): `mclmc_kernel` passed to `mclmc_find_L_and_step_size` is a **factory** `(inverse_mass_matrix) -> kernel`, where `build_kernel(logdensity_fn=…, inverse_mass_matrix=…, integrator=…)` bakes in logdensity + mass and the resulting kernel is called `kernel(rng_key, state, L, step_size)`.

**blackjax 1.6**: `mclmc_kernel` must be the **step function** itself — `blackjax.mcmc.mclmc.build_kernel(integrator=…)` returns `kernel(rng_key, state, logdensity_fn, inverse_mass_matrix, L, step_size)` — and `mclmc_find_L_and_step_size(..., logdensity_fn=…)` is now required.

So both the adaptation setup **and** the sampling loop differ between versions.

## Affected code
- `src/tengri/inference/backends/mcmc/mclmc.py` — `run_mclmc` (`kernel_factory`, `mclmc_find_L_and_step_size`), `run_adjusted_mclmc` (`_kernel_for_adaptation`, `adjusted_mclmc_find_L_and_step_size`).
- `src/tengri/inference/backends/mcmc/_shared.py` — `_mclmc_sample_scan` calls `kernel(k, s, L, step_size)` (1.3 signature); the 1.6 kernel needs `kernel(k, s, logdensity_fn, inverse_mass_matrix, L, step_size)`. Same class of change for `_adjusted_mclmc_sample_scan`.

## Suggested fix
Version-gate on `blackjax.__version__` (must keep working on both 1.3 and 1.6 since the pin allows both), threading `logdensity_fn` + `inverse_mass_matrix` into the sampling scan for the 1.6 path. **Validate the 1.6 path against the crossval/regression suite** (recover the mock truth), not just "runs + finite" — a subtly wrong kernel wiring yields a biased posterior that a smoke test won't catch.

## Repro
```python
# fresh venv with blackjax 1.6
fitter.run("mcmc_mclmc", key=key, n_warmup=40, n_samples=40)   # TypeError
```
