### ISSUE TITLE
main is red: PreintegratedGrid.flux_scale was renamed under a fixture that still passes it

### ISSUE THREAD

**Issue by suchethac** [suchethac/tengri#1897]
`main` at `2c0afb09a` fails the `test (contract, tests/contract, 2, 50)` shard:

```
7 failed, 6289 passed, 98 skipped, 2 xfailed, 2008 warnings in 2327.83s (0:38:47)

FAILED tests/contract/test_precompute_collapse_seam.py::test_fixed_axis_is_collapsed_and_free_axis_is_not
FAILED tests/contract/test_precompute_collapse_seam.py::test_nothing_collapses_when_every_axis_is_free
FAILED tests/contract/test_precompute_collapse_seam.py::test_defaults_collapse_axes_the_model_never_declared
FAILED tests/contract/test_precompute_collapse_seam.py::test_axis_count_disagreeing_with_the_grid_refuses_to_collapse
FAILED tests/contract/test_precompute_collapse_seam.py::test_grid_rank_disagreeing_with_axis_count_refuses_to_collapse
FAILED tests/contract/test_precompute_collapse_seam.py::test_no_parameters_object_is_a_silent_no_op
  TypeError: PreintegratedGrid.__init__() got an unexpected keyword argument 'flux_scale'

FAILED tests/contract/test_precompute_collapse_seam.py::test_unresolvable_axis_names_warn_instead_of_falling_silent
  Failed: DID NOT WARN. No warnings of type (<class 'tengri.config.exceptions.DeadPrecomputeAxisWarning'>,) were emitted.
```

All seven share one cause: the fixture at `tests/contract/test_precompute_collapse_seam.py:67` constructs `PreintegratedGrid(..., flux_scale=1.0)`, and that field no longer exists. The seventh is the same failure wearing a different hat — the constructor raises before the code under test runs, so the expected warning is never reached.

## Two PRs that were each green

- **#1765** (`5b2d6ad3d`) added `test_precompute_collapse_seam.py`, whose fixture passes `flux_scale=1.0`.
- **#1878** (`a276102d1`) renamed the field to `log10_flux_scale`, storing the log because the linear factor `(1+z)/(4*pi*d_L^2)` is ~1e-57 and rounds to exactly `0.0` in float32 at every distance (#1859).

#1878 was authored before that test file existed, so its sweep could not have seen the call site; #1765 merged first and #1878 landed on top. Both passed on their own branches. Nothing compared them, because branch protection runs `strict=false` — "require branches to be up to date" is off on purpose, since at this repo's queue depth forcing every PR to re-run against a moving `main` costs more than it saves.

This is the same collision class as #1862 vs #1856: **a PR carrying a call site keyed on code another PR is actively renaming.**

## Fix

`log10_flux_scale=0.0`, not `1.0` — the field is a log now, and the fixture's intent is a neutral scale, so the linear `1.0` becomes `0.0` in the log domain. The test exercises axis collapsing and never reads the value, but writing `1.0` would quietly assert a 10x flux scale.

Verified locally against `2c0afb09a`: 7 failed before, 7 passed after.

**Comment by suchethac** [comment]
Fixed on main by #1899 (`18313de03`), which changed the fixture to `log10_flux_scale=0.0` — the same value and reasoning recorded here (neutral scale is 1.0 linear, therefore 0.0 in the log domain).

Verified on `18313de03`: `tests/contract/test_precompute_collapse_seam.py` — 7 passed.

The underlying collision is worth keeping in view even though this instance is closed. #1765 added the fixture and #1878 renamed the field beneath it; each was green alone. `strict=false` on branch protection is a deliberate trade against queue depth, and this is the second instance of its cost after #1862 vs #1856. #1893 (one aggregate required context) is adjacent but does not address it — the gap is that nothing re-runs a PR against the `main` it will actually land on.
